fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "concat_native": "git://github.com/theforeman/puppet-concat.git"
    "archive": "git://github.com/camptocamp/puppet-archive.git"
  symlinks:
    "tomcat": "#{source_dir}"
