name 'proteon-java'
version '0.1.7'

author 'Sander Bilo'
license 'Apache 2.0'
project_page 'http://github.com/Proteon/puppet-java'
source 'git://github.com/Proteon/puppet-java.git'
summary 'Java module'
description 'Puppet code for deploying and configuring Oracle Java on Debian-like servers'
dependency 'puppetlabs/apt', '>=1.1.0'
